### ISSUE TITLE
Journalizing Error - Entering a second debit (or credit) and erasing it causes the balance to be NaN

### ISSUE THREAD

**Issue by wickygilb** [anthonylee83/accounting#23]
![enter value](https://user-images.githubusercontent.com/42557397/47322295-72071180-d625-11e8-84c8-493327fae37a.png)
![after deleting](https://user-images.githubusercontent.com/42557397/47322294-72071180-d625-11e8-8ba1-d59dd77d3487.png)

**Comment by anthonylee83** [comment]
This bug was fixed.
